##docker build -f Dockerfile .
##docker image ls

FROM python:3.10

ENV PYTHONBUFFERED = 1

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

COPY ./src/ /app/

CMD ["python", "app.py"]